# Simple workflow for deploying Github Pages
name: Publish Static

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - id: setup
        name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.111.3
          extended: true
      - id: build
        name: Build site
        run: hugo --minify
      - id: upload
        name: Upload artifact
        uses: actions/upload-pages-artifact@v1
      - id: deploy
        name: Deploy
        uses: actions/deploy-pages@v2
